name : Generar snake

en :
  horario : # ejecutar cada 12 horas
    - cron : " * * / 12 * * * "
  workflow_dispatch :

trabajos :
  construir :
    name : Trabajos para actualizar datos
    se ejecuta : ubuntu-latest
    pasos :
      # Animación de serpientes
      - usos : Platane / snk @ master
        id : serpiente-gif
        con :
          github_user_name : AaronLopezBarros
          svg_out_path : dist / github-contribución-grid-snake.svg

      - usos : crazy-max/ghaction-github-pages@v2.1.3
        con :
          target_branch : salida
          build_dir : dist
        env :
          GITHUB_TOKEN : $ {{secretos.GITHUB_TOKEN}}
